version: "3.8"

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: daesoo94
      MYSQL_PASSWORD: vndtkstla2
      MYSQL_DATABASE: strapi
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306

  nginx:
    image: nginx
    ports:
      - 80:80
    depends_on:
      - strapi
      - nextjs
    volumes:
      - ./compose/nginx/nginx.conf:/etc/nginx/nginx.conf

  strapi:
    build:
      context: .
      dockerfile: ./compose/strapi/Dockerfile-dev
    command: sh /start-dev.sh
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=daesoo94
      - DATABASE_PASSWORD=vndtkstla2
      - BASE_URL=http://localhost
    depends_on:
      - mysql
    ports:
      - 1337:1337
    volumes:
      - ./strapi/:/home/service/strapi/
      - strapi_node_modules:/home/service/strapi/node_modules/

  nextjs:
    build:
      context: .
      dockerfile: ./compose/nextjs/Dockerfile-dev
    command: sh /start-dev.sh
    environment:
      - SSR_API_URL=http://strapi:1337
    ports:
      - 3000:3000
    volumes:
      - ./nextjs/:/home/service/nextjs/
      - nextjs_node_modules:/home/service/nextjs/node_modules/

volumes:
  mysqldata:
  strapi_node_modules:
  nextjs_node_modules: